version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Artur.14022005
      MYSQL_DATABASE: parserbootnew
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    environment:
      - JWT_SECRET=IamSuperMegaPuperSecretCodeMotherFucker!
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://discovery-service:8761/eureka
    depends_on:
      - rabbitmq
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=IamSuperMegaPuperSecretCodeMotherFucker!
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://discovery-service:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - QUEUE_LOGIN=LoginQueue
      - QUEUE_REGISTER=RegisterQueue
    depends_on:
      - rabbitmq
    networks:
      - app-network

  front-service:
    build: ./front-service
    container_name: front-service
    ports:
      - "8001:8001"
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - app-network

  heroes-stats-service:
    build: ./heroes-stats-service
    container_name: heroes-stats-service
    ports:
      - "8002:8002"
    environment:
      - spring.application.name=Heroes-Stats-Service
      - server.port=8002
      - spring.datasource.url=jdbc:mysql://mysql:3306/parserbootnew
      - spring.datasource.username=user
      - spring.datasource.password=userpassword
      - spring.jpa.generate-ddl=true
      - spring.jpa.hibernate.ddl.auto=update
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - queue.decrementLimitForUser=decrementLimitForUserQueue
      - queue.stats=StatsQueue
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network

  tournament-service:
    build: ./tournament-service
    container_name: tournament-service
    ports:
      - "8003:8003"
    environment:
      - spring.application.name=Tournament-Service
      - server.port=8003
      - spring.datasource.url=jdbc:mysql://mysql:3306/parserbootnew
      - spring.datasource.username=user
      - spring.datasource.password=userpassword
      - spring.jpa.generate-ddl=true
      - spring.jpa.hibernate.ddl.auto=update
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - queue.stats=StatsQueue
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8004:8004"  # Додано порт 8004
    environment:
      - spring.application.name=User-Service
      - server.port=8004
      - spring.datasource.url=jdbc:mysql://mysql:3306/parserbootnew
      - spring.datasource.username=user
      - spring.datasource.password=userpassword
      - spring.jpa.generate-ddl=true
      - spring.jpa.hibernate.ddl.auto=update
      - jwtSecret=IamSuperMegaPuperSecretCodeMotherFucker!
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - queue.login=LoginQueue
      - queue.register=RegisterQueue
      - queue.decrementLimitForUser=decrementLimitForUserQueue
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - app-network

networks:
  app-network:
    external: true
